version: 2.1

jobs:
  test-node:
    parameters:
      node-version:
        type: string

    docker:
      - image: cimg/node:<< parameters.node-version >>

    steps:
      - checkout

      - restore_cache:
          name: Restore node package cache
          keys:
            - node-packages-v1-{{ checksum "package-lock.json" }}
            - node-packages-v1-

      - run:
          name: Install test dependencies
          command: |
            npm install --engine-strict
            npm install --no-save jest-junit

      - save_cache:
          name: Save node package cache
          key: node-packages-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm/

      - run:
          name: Run tests
          command: |
            mkdir -p ./test-results/junit

            npx eslint ./
            npx jest --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./test-results/junit/
            JEST_JUNIT_OUTPUT_NAME: jest-results.xml

      - store_test_results:
          path: ./test-results/

  test-python:
    parameters:
      python-version:
        type: string

    docker:
      - image: cimg/python:<< parameters.python-version >>

    steps:
      - checkout

      - restore_cache:
          name: Restore python package cache
          keys:
            - python-packages-v1-{{ checksum "Pipfile.lock" }}
            - python-packages-v1-

      - run:
          name: Install test dependencies
          command: |
            pipenv sync --dev

      - save_cache:
          name: Save python package cache
          key: python-packages-v1-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.virtualenvs

      - run:
          name: Run tests
          command: |
            pipenv run flake8
            pipenv run mypy src_py/grndwork_api_client
            pipenv run python3 -m pytest

      - store_test_results:
          path: ./test-results/

  build:
    docker:
      - image: cimg/python:3.10-node

    steps:
      - checkout

      - restore_cache:
          name: Restore node package cache
          keys:
            - node-packages-v1-{{ checksum "package-lock.json" }}
            - node-packages-v1-

      - restore_cache:
          name: Restore python package cache
          keys:
            - python-packages-v1-{{ checksum "Pipfile.lock" }}
            - python-packages-v1-

      - run:
          name: Install build dependencies
          command: |
            npm install
            pipenv sync --dev

      - save_cache:
          name: Save node package cache
          key: node-packages-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm/

      - save_cache:
          name: Save python package cache
          key: python-packages-v1-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.virtualenvs

      - run:
          name: Run Build
          command: |
            npm run build

      - run:
          name: Publish tagged release
          command: |
            if [[ $CIRCLE_TAG =~ ^v[0-9].* ]]; then
              case $CIRCLE_TAG in
                *alpha*)
                  npm publish --access public --tag alpha
                  ;;
                *beta*)
                  npm publish --access public --tag beta
                  ;;
                *rc*)
                  npm publish --access public --tag next
                  ;;
                *)
                  npm publish --access public --tag latest
                  ;;
              esac
            fi

workflows:
  main:
    jobs:
      - test-node:
          matrix:
            parameters:
              node-version:
                - "18.19"
                - "20.11"
                - "21.6"
          filters:
            tags:
              only: /v[0-9].*/

      - test-python:
          matrix:
            parameters:
              python-version:
                - "3.10"
                - "3.11"
                - "3.12"
          filters:
            tags:
              only: /v[0-9].*/

      - build:
          requires:
            - test-node
            - test-python
          filters:
            tags:
              only: /v[0-9].*/
