version: 2

jobs:
  test:
    docker:
      - image: cimg/python:3.9-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-packages-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-packages-v1-{{ .Branch }}-
            - node-packages-v1-

      - restore_cache:
          keys:
            - pipenv-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - pipenv-packages-v1-{{ .Branch }}-
            - pipenv-packages-v1-
      - run:
          command: |
            npm install
      - save_cache:
          key: node-packages-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm/
      - save_cache:
          key: pipenv-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.virtualenvs
      - run:
          command: |
            npm test

  build:
    docker:
      - image: cimg/python:3.9-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-packages-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-packages-v1-{{ .Branch }}-
            - node-packages-v1-
      - run:
          name: Install Dependencies
          command: |
            npm ci
      - save_cache:
          key: node-packages-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm/
      - run:
          name: Run Build
          command: |
            npm run build

      - run:
          name: Publish When Tagged Release
          command: |
            if [[ $CIRCLE_TAG =~ ^v[0-9].* ]]; then
              case $CIRCLE_TAG in
                *alpha*)
                  npm publish --access public --tag alpha
                  ;;
                *beta*)
                  npm publish --access public --tag beta
                  ;;
                *rc*)
                  npm publish --access public --tag next
                  ;;
                *)
                  npm publish --access public --tag latest
                  ;;
              esac
            fi

workflows:
  version: 2
  main:
    jobs:
      - test:
          filters:
            tags:
              only: /v[0-9].*/

      - build:
          requires:
            - test
          filters:
            tags:
              only: /v[0-9].*/
